version: "3.7"
services:
  web:
    build: ./nginx
    volumes:
     - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    ports:
     - "8080:80"
  node:
    build: ./node
    ports:
     - "3000:3000"
